language: java

jdk:
  - oraclejdk8

sudo: false
install: true

addons:
  sonarcloud:
    organization: nickrobison-github
    token:
      secure: "VGoGGAzSbztXz3frL7Ey2igEX6Vir9zVUarULma8OxSAN5JzABa6FChqsrv3hwCkWIu56h/dt0zhlk0wWwyV4JDoxsxQ7x5u5JDEzbfg+8ajVVUZZJRT8RwXDze48p79AsmOWpD98Te9iWkJg983KIbBh4pTupA3qAXQ/umMfOlK+qCnB9NKWKdLXOs7BbONv/DhC1pY2lBqwU4uvFJhObCCqWNL3GIIfv+WJkEqOuWFs7AbwRnpCl1Tf39VWvSf9xWBRelC4hFhhM9V0KNtmfxQtQUEpSaz6xxXVjs53j96Ir+NXOd/baqVJwd2xtjXK/uOivnMHc25Y5dwesfnM0gPgdDqKkdyhAjsLFJDfkHC9q//klh3Qn2CLJPbpXwhasrswej8QaE4B63plHwGD/XybJ0kNeZ5ibt7mAd00VELCGbJZzusFdVxMfkZbs1i6krujDVlooBxJHTF/W+Vw+/hzzo5cjEgNcOMljAubpMGw1hzz0V6o57Fqn7u3WGQmEmjPKLqAYbHKTw/vbXCPLVJjcjzuqWjGAoVCzn+/rtpEfPWH0ZzvQyJXwk/NhgfsLJbHDr2nvBdUB1gZgVOKyP8gEc1zMXf3K9eHhWk+/9yXXEVw8rj4WszwkfLtgkA9fbO13lbCoS6yZHEEUMZjZAlMF018l3FGhF/bzVP6UI="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
