/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */

allprojects {
    group = "com.nickrobison"
    version = "0.3.2-SNAPSHOT"

    apply(plugin = "java")

    repositories {
        jcenter()
    }

    tasks.withType<JavaCompile> {
        sourceCompatibility = "1.8"
        targetCompatibility = "1.8"
    }
}